###############
### General ###
###############

set -g default-terminal "tmux-256color"
set-option -sa terminal-features ",xterm-256-color:RGB"

# Left length
set -g status-left-length 0

# Statusbar position
set -g status-position bottom

# Disable mouse
set -g mouse on

# Reload config file
bind r source-file ~/.config/tmux/tmux.conf

#############
### THEME ###
#############

# Variables for theming
set -g @icon-tmux ""
set -g @icon-left-full ""
set -g @icon-left-empty ""
set -g @icon-right-full ""

# Set elements in statusline
set -g status-left "#[bg=colour93,fg=colour15] #{@icon-tmux} #[bg=colour92,fg=colour93]#{@icon-left-full}#[fg=colour15,bg=colour92] #S #[fg=colour92,bg=colour0]#{@icon-left-full}"
set -g status-right "#[bg=default,fg=colour96]#{@icon-right-full}#[bg=colour96,fg=colour100]#{@icon-right-full}#[bg=colour100,fg=colour103]#{@icon-right-full}#[bg=colour103,fg=colour15] #H "

# Remove spacing
set -g window-status-separator ""

# default statusbar colors
set -g status-style bg=colour0,fg=colour15

# current window title colors
set-window-option -g window-status-current-style NONE
set-window-option -g window-status-current-format "#[fg=colour0,bg=colour63]#{@icon-left-full}#[fg=colour15,bg=colour63] #I #[fg=colour63,bg=colour69]#{@icon-left-full}#[fg=colour15,bg=colour69] #W #[fg=colour69,bg=colour0]#{@icon-left-full}"

# default window title colors
set-window-option -g window-status-style "bg=default,fg=colour245"
set-window-option -g window-status-format "  #I #{@icon-left-empty} #W  "

# pane border
set-option -g pane-border-style fg=colour81
set-option -g pane-active-border-style fg=colour84

# message text
set-option -g message-style bg=colour81,fg=colour17

# pane number display
set-option -g display-panes-active-colour colour203
set-option -g display-panes-colour colour84

# clock
set-window-option -g clock-mode-colour colour205

###############
### Plugins ###
###############

# List plugins
set -g @plugin 'tmux-plugins/tpm'

# Always should be at the bottom
run '~/.tmux/plugins/tpm/tpm'

